[theme]
base = "light"
primaryColor = "#087f78"
backgroundColor = "#f6f8fb"
secondaryBackgroundColor = "#edf2f6"
textColor = "#132238"
font = "sans-serif"

[server]
headless = true
maxUploadSize = 15

[client]
toolbarMode = "viewer"
